<?php

namespace App\Services\PayoffCalculator\Actions;

use Carbon\Carbon;
use App\Models\User;
use App\Models\Payment;
use App\Models\PayoffCalculatorRun;
use App\Services\PayoffCalculator\PayoffCalculator;
use Illuminate\Support\Str;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

/**
 * Save the results of a PayoffCalculator run
 */
class SavePayoffCalculations
{
    /**
     * User who owns the debts used in the PayoffCalculator run
     * 
     * @var \App\Models\User 
     */
    protected $user;

    /**
     * The PayoffCalculator instance
     * 
     * @var PayoffCalculator
     */
    protected $payoffCalculator;

    /**
     * PayoffCalculatorRun model saved with results of the PayoffCalculator run
     * 
     * @var \App\Models\PayoffCalculatorRun
     */
    protected $payoffCalculatorRun;

    /**
     * Save the results of a PayoffCalculator run
     * 
     * Summary of execute
     * @param \App\Models\User $user
     * @param \App\Services\PayoffCalculator\PayoffCalculator $engine
     * @return void
     */
    public function execute(User $user, PayoffCalculator $engine): void
    {
        $this->user = $user;
        $this->payoffCalculator = $engine;

        // if nothing to save, we're done
        $payments = $this->payoffCalculator->getPayments();
        if ($payments->count() == 0) {
            return;
        }

        // FIXME: try catch the saves ??? if any fail, do what?
        //  - maybe serialize as a job for later?
        DB::transaction(function () {
            // the order of these steps is important (mostly we need run_id first)
            $this->deleteCurrentPayments();
            $this->savePayoffRun();
            $this->savePayoffPayments();
            $this->saveFinancialFreedomDate();
        }, 5);  // retry 5 times if deadlock occurs
    }

    /**
     * delete all rows for the current year/month forward
     */
    protected function deleteCurrentPayments() {
        $strategy = $this->payoffCalculator->getPayoffStrategy();

        $firstPaymentDate = $this->payoffCalculator
            ->getPayments()
            ->min(fn ($debt) => $debt->first()->payment_date);

        Payment::where('user_id', $this->user->id)
            ->where('payoff_strategy', '=', $strategy)
            ->where('payment_date', '>=', $firstPaymentDate->toDateTimeString())
            ->delete();
    }

    /**
     * Record this run along with it's stats and input debs
     * 
     * @return void
     */
    protected function savePayoffRun() {
        $runStats = $this->payoffCalculator->getStats();

        $this->payoffCalculatorRun = PayoffCalculatorRun::create([
            'user_id' => $this->user->id,
            'financial_freedom_date' => $runStats['financial_freedom_date'],
            'payoff_strategy' => $runStats['payoff_strategy'],
            'debts' => $debts = $this->user->debts, //->toArray(),
            'run_stats' => $runStats,
            'payoff_results' => $this->payoffCalculator->getPayments(),
        ]);
    }

    /**
     * Save the Payments generated by this run
     * 
     * @return void
     */
    protected function savePayoffPayments()
    {
        $payments = $this->payoffCalculator->getPayments();
        foreach ($payments as $debt) {
            $this->savePayments($debt);
        }
    }

    /**
     * Bulk save a collection of Payment models
     * 
     * @param \Illuminate\Support\Collection $payments
     * @return void
     */
    protected function savePayments(Collection $payments): void
    {
        $now = Carbon::now();

        // Add missing data.  Also, when using bulk inserts, Eloquent Model
        // timestamps and the HasUlids primary key trait will not run, so we set
        // those as well.
        $common = [
            'user_id' => $this->user->id,
            'run_id' => $this->payoffCalculatorRun->id,
            'payoff_strategy' => $this->payoffCalculator->getPayoffStrategy(),
            'created_at' => $now,
            'updated_at' => $now
        ];

        // transform the collection into arrays, adding missing data
        $records = $payments->map(function ($payment) use ($common) {
            return array_merge($payment->toArray(), [
                'id' => strtolower((string) Str::ulid()),
                ...$common,
            ]);
        });

        // chunk the inserts to avoid memory issues with large datasets
        $records->chunk(100)->each(function ($chunk) {
            Payment::insert($chunk->toArray());
        });
    }

    protected function saveFinancialFreedomDate() {
        $userStrategy = $this->user->payoffOptions->payoff_strategy;
        $runStrategy = $this->payoffCalculator->getPayoffStrategy();

        // only save the financial freedom date if this run is using the user's payoff strategy
        if ($runStrategy == $userStrategy) {
            $this->user->financial_freedom_date = $this->payoffCalculator->getStats()['financial_freedom_date'];
            $this->user->save();
        }
    }
}
